- name: Remove VM
  hosts: localhost
  connection: local
  tasks:
    - name: Delete VM
      azure_rm_virtualmachine:
        resource_group: "rg-{{ userId }}"
        name: "myVM"
        remove_on_absent: all
        state: absent